### PR TITLE
Auto focus elements in modals

### PR DESCRIPTION
**Pull request by jessebofill**
I decided to revisit this issue #28 and managed to get it working. I also made it so that the name input text box also takes focus when first opening EditTabModal, as opposed to the tooltip icon we added.

### CODE REVIEW

**Comment by jessebofill** [comment]
I also want to auto focus the add filter button in edit merge filter modal too but I haven’t messed with that yet.

**Comment by Tormak9970** [comment]
> I also want to auto focus the add filter button in edit merge filter modal too but I haven’t messed with that yet. 

Sounds good. I'll test when I have a chance

**Comment by Tormak9970** [comment]
@jessebofill I'll test this tomorrow

**Comment by Tormak9970** [comment]
works great! Definitely improves the ux

**Pull request merged**
